spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/unibell_cs_db}
    username: ${SPRING_DATASOURCE_USERNAME:username}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  liquibase:
    enabled: true
    default-schema: client_service
    change-log: db/changelog/db.changelog-master.yaml

logging:
  level:
    root: INFO
    org.springframework: INFO
  logstash-host: ${LOGSTASH-HOST:localhost:4560}
  config: classpath:logback-spring.xml
